import Head from 'next/head';
import About from '../components/About';
import Contact from '../components/Contact';
import Main from '../components/Main';
import Projects from '../components/Projects';
import Skills from '../components/Skills';

export default function Home() {
	return (
		<>
			<Head>
				<title>Ben | web Developer</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main id="main">
				<Main />
				<About />
				<Skills />
				<Projects />
				<Contact />
			</main>
		</>
	);
}
